### ISSUE TITLE
Unable to update: LazyLibrarian failed to update: error Error -3 while decompressing: invalid literal/lengths set. Restarting.

### ISSUE THREAD

**Issue by CasperH2O** [DobyTang/LazyLibrarian#1081]
### LazyLibrarian version number (at the bottom of config page)
urrent Version: No Version File : Latest Version: 55cf15e3e6cd4627beb169ee7a322ce0cf940ea0
Just downloaded the zip for:  55cf15e 
### Operating system used (windows, mac, linux, NAS type)
Windows 10 
### Interface in use (default, bookstrap)
Default
### Which api (Goodreads, GoogleBooks, both)
GoogleBooks
### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
Zip file.
### Relevant debug log with api keys and any passwords redacted

```
19-okt-2017 21:09:01 - INFO :: MAIN : versioncheck.py:logmsg:37 : [VersionCheck] -  You are running an unknown version of lazylibrarian. Run the updater to identify your version
19-okt-2017 21:09:01 - INFO :: MAIN : LazyLibrarian.py:main:189 : Starting LazyLibrarian on port: 5299, webroot ""
19-okt-2017 21:09:01 - INFO :: MAIN : webStart.py:initialize:57 : Starting LazyLibrarian web server on http://0.0.0.0:5299/
19-okt-2017 21:09:02 - INFO :: DB_UPGRADE : dbupgrade.py:dbupgrade:127 : Creating new database, version 23
19-okt-2017 21:09:03 - INFO :: DB_UPGRADE : dbupgrade.py:dbupgrade:349 : Database upgraded to version 23
19-okt-2017 21:09:37 - INFO :: MAIN : __init__.py:logmsg:1287 : LazyLibrarian is updating...
INFO:lazylibrarian:MAIN : __init__.py:logmsg:1287 : LazyLibrarian is updating...
19-okt-2017 21:09:37 - INFO :: MAIN : versioncheck.py:logmsg:37 : (update) Downloading update from: https://github.com/dobytang/lazylibrarian/tarball/master
INFO:lazylibrarian:MAIN : versioncheck.py:logmsg:37 : (update) Downloading update from: https://github.com/dobytang/lazylibrarian/tarball/master
19-okt-2017 21:09:39 - INFO :: MAIN : versioncheck.py:logmsg:37 : (update) Extracting fileC:\Users\<username removed>\Desktop\LazyLibrarian-master\LazyLibrarian-master\master
INFO:lazylibrarian:MAIN : versioncheck.py:logmsg:37 : (update) Extracting fileC:\Users\<username removed>\Desktop\LazyLibrarian-master\LazyLibrarian-master\master
19-okt-2017 21:09:39 - WARNING :: MAIN : __init__.py:logmsg:1285 : LazyLibrarian failed to update: error Error -3 while decompressing: invalid literal/lengths set. Restarting.
WARNING:lazylibrarian:MAIN : __init__.py:logmsg:1285 : LazyLibrarian failed to update: error Error -3 while decompressing: invalid literal/lengths set. Restarting.
19-okt-2017 21:09:39 - INFO :: MAIN : __init__.py:logmsg:1287 : LazyLibrarian is restarting ...
NFO:lazylibrarian:MAIN : __init__.py:logmsg:1287 : LazyLibrarian is restarting ...
```

So I downloaded the zip file three times. Unzipped twize with regular Windows Explorer and the third time with the latest 7zip. Just started them and hit the update button at the bottom right.

What I did notice was that the actual log message seems to be missing a space, it states "Extracting fileC:..." is that relevant?

Should I make a debug log?
I noticed during boot the missing SSL and encryption python packeges message, should I pip install those?

**Comment by philborman** [comment]
The zipfile seemed to download ok, the problem seems to be unpacking the next version. Because you installed from a zip file we don't know what version of lazylibrarian you have (we don't know how old the zipfile is) so we force an immediate upgrade to current version. This is failing to unpack for unknown reason. I have added a little more debugging to the code, might help. The other way around it is to tell it we _do_ know what version you have, create a file called "version.txt" in the main lazylibrarian folder (the one containing LazyLibrarian.py) 
In it put the version number,  55cf15e3e6cd4627beb169ee7a322ce0cf940ea0

The log message was missing a space as you noticed, fixed now, will update the main branch tomorrow.

The debug log won't help (there are no extra debug messages in this section)

The ssl and encryption packages are needed for goodreads as they are changing to force all traffic over https in December. You can pip install them early.

**Comment by CasperH2O** [comment]
> The zipfile seemed to download ok, the problem seems to be unpacking the next version. Because you installed from a zip file we don't know what version of lazylibrarian you have (we don't know how old the zipfile is) so we force an immediate upgrade to current version. This is failing to unpack for unknown reason. I have added a little more debugging to the code, might help.
> UPDATE
> Just noticed you are running windows. The forced upgrade downloads a tarfile, does your windows installation include tarfile support?

Nice catch! I'm running a fairly vanilla Windows 10 so I'm pretty sure it does not know how to handle tar files. 7zip is installed, but I don't think that command line tar commands work by default. I'll investigate.

> The other way around it is to tell it we do know what version you have, create a file called "version.txt" in the main lazylibrarian folder (the one containing LazyLibrarian.py)
> In it put the version number, 55cf15e3e6cd4627beb169ee7a322ce0cf940ea0

I can do that, but then I still won't be able to update?

> The log message was missing a space as you noticed, fixed now, will update the main branch tomorrow.

Nice.

> The debug log won't help (there are no extra debug messages in this section)
> 
> The ssl and encryption packages are needed for goodreads as they are changing to force all traffic over https in December. You can pip install them early.

Ok! I'll get right on that.

I notice there are still a couple of prerequisites for running LazyLibrarian and some more "how to..." info could be useful. Can I help out with that somehow?

**Comment by philborman** [comment]
Looks like tarfile processing is included by default in python. If it's not on windows I think we should throw an error before we get to that point. Puzzled. I have added some extra debugging around the tarfile unpacking code, and we now leave the downloaded tarfile on exit if we fail, so it should be possible to check if the tarfile is ok.

Creating a version.txt file will not stop future updates, as we use the presence of the file tell if we're a new install, and the contents of the file to tell if we are up to date, so next time you try to upgrade we compare the version in the file with the latest version reported by github.

We could definitely do with more documentation, and I'm slowly trying to work out the prerequisites for lazylibrarian, I don't know of an easy way to check, especially what minimum versions of libraries are needed. I found a few and added warnings on startup. By the time we get to December and goodreads switches to https only, quite a few older systems (particularly NAS devices) are running very old software which the manufacturers do not update so they will break as they don't support https/ssl/encryption. There sill need to be more warnings in place by then!

**Comment by CasperH2O** [comment]
> Looks like tarfile processing is included by default in python. If it's not on windows I think we should throw an error before we get to that point. Puzzled. I have added some extra debugging around the tarfile unpacking code, and we now leave the downloaded tarfile on exit if we fail, so it should be possible to check if the tarfile is ok.

I installed a basic Python 2.7 for Windows:
```
python --version
Python 2.7.14
```

I did an import of tarfile, that seemed to work. What command/module are you using to extract, I can do some experiments? Sure when you have the new version up I can run some tests.

> Creating a version.txt file will not stop future updates, as we use the presence of the file tell if we're a new install, and the contents of the file to tell if we are up to date, so next time you try to upgrade we compare the version in the file with the latest version reported by github.

I meant my reply more along the lines of, that it would help for now, but won't solve the actual update problem. Good to know either way.

> We could definitely do with more documentation

Any way I could help?

**Comment by philborman** [comment]
We just use...
            tar = tarfile.open(tar_download_path)
            tar.extractall(update_dir)
            tar.close()
where tar_download_path in your case is C:\Users\<username removed>\Desktop\LazyLibrarian-master\LazyLibrarian-master\master
and update_dir is a new empty directory to unpack into.

> We could definitely do with more documentation
> > Any way I could help?
There is a wiki on the lazylibrarian git page, if you feel like adding anything please do, any help gratefully received.

**Comment by CasperH2O** [comment]
Downloaded a fresh version with the extra debug and hit update, seems to work OK. I checked the changes and adjusted the binary mode back to only "w" on line 438. Then I got the error again. So I think you caught it!

Additionally I tested on another Windows 10 machine, which was running Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) with the version from yesterday. There the update went fine on the first go. Odd.

```
20-okt-2017 15:15:44 - INFO :: UPDATES : versioncheck.py:logmsg:37 : [VersionCheck] -  Comparing currently installed version with latest github version
20-okt-2017 15:15:44 - WARNING :: UPDATES : versioncheck.py:logmsg:41 : (getCommitDifferenceFromGit) KeyError -  could not get difference status from GitHub
20-okt-2017 15:15:44 - INFO :: UPDATES : versioncheck.py:logmsg:37 : [VersionCheck] -  You are running an unknown version of lazylibrarian. Run the updater to identify your version
20-okt-2017 15:15:55 - INFO :: CONFIG_WRITE : __init__.py:config_write:938 : Config file [C:\Users\
<removed>\Software\Applicaties\LazyLibrarian-master-00853d0\config.ini] has been updated
20-okt-2017 15:16:07 - INFO :: MAIN : __init__.py:logmsg:1287 : LazyLibrarian is updating...
INFO:lazylibrarian:MAIN : __init__.py:logmsg:1287 : LazyLibrarian is updating...
20-okt-2017 15:16:07 - INFO :: MAIN : versioncheck.py:logmsg:37 : (update) Downloading update from: https://github.com/dobytang/lazylibrarian/tarball/master
INFO:lazylibrarian:MAIN : versioncheck.py:logmsg:37 : (update) Downloading update from: https://github.com/dobytang/lazylibrarian/tarball/master
20-okt-2017 15:16:09 - INFO :: MAIN : versioncheck.py:logmsg:37 : (update) Extracting file C:\Users\<removed>\Software\Applicaties\LazyLibrarian-master-00853d0\master
INFO:lazylibrarian:MAIN : versioncheck.py:logmsg:37 : (update) Extracting file C:\Users\<removed>\Software\Applicaties\LazyLibrarian-master-00853d0\master
20-okt-2017 15:16:09 - INFO :: MAIN : versioncheck.py:logmsg:37 : (update) Deleting file C:\Users\<removed>\Software\Applicaties\LazyLibrarian-master-00853d0\master
INFO:lazylibrarian:MAIN : versioncheck.py:logmsg:37 : (update) Deleting file C:\Users\<removed>\Software\Applicaties\LazyLibrarian-master-00853d0\master
DEBUG:lazylibrarian:MAIN : versioncheck.py:logmsg:39 : (updateVersionFile) Updating [C:\Users\<removed>\Software\Applicaties\LazyLibrarian-master-00853d0\version.txt] with value [00853d052dbc697356e5d319812892364c12f472]
20-okt-2017 15:16:11 - INFO :: MAIN : __init__.py:logmsg:1287 : Lazylibrarian version updated
INFO:lazylibrarian:MAIN : __init__.py:logmsg:1287 : Lazylibrarian version updated
20-okt-2017 15:16:11 - INFO :: CONFIG_WRITE : __init__.py:config_write:938 : Config file [C:\Users\<removed>\Software\Applicaties\LazyLibrarian-master-00853d0\config.ini] has been updated
INFO:lazylibrarian:CONFIG_WRITE : __init__.py:config_write:938 : Config file [C:\Users\<removed>\Software\Applicaties\LazyLibrarian-master-00853d0\config.ini] has been updated
20-okt-2017 15:16:11 - INFO :: CONFIG_WRITE : __init__.py:logmsg:1287 : LazyLibrarian is restarting ...
INFO:lazylibrarian:CONFIG_WRITE : __init__.py:logmsg:1287 : LazyLibrarian is restarting ...
```

**Comment by philborman** [comment]
Not sure about the 'w' vs 'wb', the saved files are the same on linux, same length, same checksum whichever mode is used.

**Comment by dfrederiksen** [comment]
I too am having the same issue.  What do I need to change to get the update to work?  I am using WinRAR for TAR support on the system but after reading this thread I changed to 7Zip.


**Current Version:** ec9a96f583b6096e16eb9e6ebe787059d94d4428

**Operating system used (windows, mac, linux, NAS type)**

Windows 7 Pro 32bit

**Interface in use (default, bookstrap)**

Default

**Which api (Goodreads, GoogleBooks, both)**

None

**Source of your LazyLibrarian installation (git, zip file, 3rd party package)**

Zip file.

**Relevant debug log with api keys and any passwords redacted**

WARNING :: MAIN : __init__.py:logmsg:1283 : LazyLibrarian failed to update: error Error -3 while decompressing: invalid literal/lengths set. Restarting.

**Comment by philborman** [comment]
I think just downloading the latest zip should fix it. Please report back if that doesn't work.

**Comment by dfrederiksen** [comment]
Still pretty new.  What file[s] should I keep to retain my config and library?

**Comment by CasperH2O** [comment]
I just tested it with my main LazyLibrarian files etc. I stopped everything, changed the file to have "wb" instead of "w" and it worked like a charm. Reading the Python docs apparently text based "t" is the default, but that does not really explain why it works fine on the other machine. See also https://www.programiz.com/python-programming/file-operation

**Comment by philborman** [comment]
Simplest is to rename your current lazylibrarian folder, unzip the new one, and them copy config.ini lazylibrarian.db and cache into the new folder.
cache is useful to copy over as it saves having to re-download a lot of info. It would rebuild itself eventually, but saves a lot of internet bandwidth if you copy it over.

Best solution for future is to not keep those files in the lazylibrarian folder, keep them in a user folder instead and start lazylibrarian with --datadir pointing to the user folder

**Comment by dfrederiksen** [comment]
Worked like a charm.  Didn't think about using the --datadir switch.  I will work on that.

Thank you very much.  That was amazing fast support.
