### ISSUE TITLE
Missing Modules?

### ISSUE THREAD

**Issue by famewolf** [DobyTang/LazyLibrarian#1457]
To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

### There is a built-in debug log creator on the logs page which makes it easy to provide this information
* To use it, first go to the log page and make sure debug logging is OFF
* Now press the "Start debug log" button
* Go and do whatever you need to recreate the error
* Go back to the log page and press "Save debug log"
* You can now turn debug logging off again if you want
* The saved log file will be found in your lazylibrarian log directory called debug.zip
* It will contain all lines logged since you pressed "Start debug log" with any passwords and api keys removed
* Attach the zip file to your bug report. 

I have lazylibrarian running on freenas using the pre-compiled package.  I've been doing the normal updates for a long time now..when I went into it this time it told me it could not get the latest git and when I browsed the log I saw:

2018-06-11 03:00:23 | WARNING | (getLatestVersion_FromGit) Could not get the latest commit from github
-- | -- | --
2018-06-11 03:00:22 | WARNING | cryptography: module missing
2018-06-11 03:00:22 | WARNING | OpenSSL missing module/attribute: No module named OpenSSL.SSL
2018-06-11 03:00:22 | WARNING | pyOpenSSL: module missing
2018-06-11 03:10:29 | ERROR | Unhandled exception in processDir: Traceback (most recent call last): File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 455, in processDir res = unpack_archive(os.path.join(pp_path, f), pp_path, matchtitle) File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 197, in unpack_archive if not os.path.isfile(pp_path): # regular files only File "/usr/pbi/lazylibrarian-amd64/lib/python2.7/genericpath.py", line 29, in isfile st = os.stat(path) UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 145: ordinal not in range(128)
-- | -- | --

Obviously I'm concerned.  Is there anything I can do to get things back on track or am I going to have to "start fresh?"

**Comment by philborman** [comment]
Couldn't get the latest git is usually a communication issue, often temporary. If it continues, turn debug log on and use the "check version" button in config. That should report what the problem is.

The missing modules are only a warning, see the lazylibrarian wiki page on SSL
Potentially could be a problem in the future if goodreads only allow https, which was announced last December but doesn't seem to have happened yet.

The unhandled exception in processdir needs fixing though.

**Comment by philborman** [comment]
The unhandled exception should be fixed in the next release, probably tomorrow.

**Comment by famewolf** [comment]
Thanks for the quick followup!  I'll have to enable debugging to figure out why it's still "Unable to get latest version from GITHub".   I verified no proxy was set that could be interfering.  It's still pulling it author data so I know it has internet..so just the upgrade part is having problems.

**Comment by philborman** [comment]
Any news on the upgrade issue?

**Comment by famewolf** [comment]
![screenshot_20180630_144243](https://user-images.githubusercontent.com/4558832/42129130-232d90f6-7c8a-11e8-8dc6-e3240bbed08a.png)

I enabled debug mode but don't see anything in the log to explain why it can't connect to update.  The error's are still occuring because it can't download the latest version where it's been fixed....

[code]

2018-06-30 17:16:50 | ERROR | Unhandled exception in processDir: Traceback (most recent call last): File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 455, in processDir res = unpack_archive(os.path.join(pp_path, f), pp_path, matchtitle) File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 197, in unpack_archive if not os.path.isfile(pp_path): # regular files only File "/usr/pbi/lazylibrarian-amd64/lib/python2.7/genericpath.py", line 29, in isfile st = os.stat(path) UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 145: ordinal not in range(128)
-- | -- | --
2018-06-30 17:06:50 | ERROR | Unhandled exception in processDir: Traceback (most recent call last): File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 455, in processDir res = unpack_archive(os.path.join(pp_path, f), pp_path, matchtitle) File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 197, in unpack_archive if not os.path.isfile(pp_path): # regular files only File "/usr/pbi/lazylibrarian-amd64/lib/python2.7/genericpath.py", line 29, in isfile st = os.stat(path) UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 145: ordinal not in range(128)
2018-06-30 16:56:50 | ERROR | Unhandled exception in processDir: Traceback (most recent call last): File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 455, in processDir res = unpack_archive(os.path.join(pp_path, f), pp_path, matchtitle) File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 197, in unpack_archive if not os.path.isfile(pp_path): # regular files only File "/usr/pbi/lazylibrarian-amd64/lib/python2.7/genericpath.py", line 29, in isfile st = os.stat(path) UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 145: ordinal not in range(128)
2018-06-30 16:46:50 | ERROR | Unhandled exception in processDir: Traceback (most recent call last): File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 455, in processDir res = unpack_archive(os.path.join(pp_path, f), pp_path, matchtitle) File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 197, in unpack_archive if not os.path.isfile(pp_path): # regular files only File "/usr/pbi/lazylibrarian-amd64/lib/python2.7/genericpath.py", line 29, in isfile st = os.stat(path) UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 145: ordinal not in range(128)
2018-06-30 16:36:50 | ERROR | Unhandled exception in processDir: Traceback (most recent call last): File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 455, in processDir res = unpack_archive(os.path.join(pp_path, f), pp_path, matchtitle) File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 197, in unpack_archive if not os.path.isfile(pp_path): # regular files only File "/usr/pbi/lazylibrarian-amd64/lib/python2.7/genericpath.py", line 29, in isfile st = os.stat(path) UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 145: ordinal not in range(128)
2018-06-30 16:26:50 | ERROR | Unhandled exception in processDir: Traceback (most recent call last): File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 455, in processDir res = unpack_archive(os.path.join(pp_path, f), pp_path, matchtitle) File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 197, in unpack_archive if not os.path.isfile(pp_path): # regular files only File "/usr/pbi/lazylibrarian-amd64/lib/python2.7/genericpath.py", line 29, in isfile st = os.stat(path) UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 145: ordinal not in range(128)
2018-06-30 16:16:50 | ERROR | Unhandled exception in processDir: Traceback (most recent call last): File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 455, in processDir res = unpack_archive(os.path.join(pp_path, f), pp_path, matchtitle) File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 197, in unpack_archive if not os.path.isfile(pp_path): # regular files only File "/usr/pbi/lazylibrarian-amd64/lib/python2.7/genericpath.py", line 29, in isfile st = os.stat(path) UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 145: ordinal not in range(128)
2018-06-30 16:06:50 | ERROR | Unhandled exception in processDir: Traceback (most recent call last): File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 455, in processDir res = unpack_archive(os.path.join(pp_path, f), pp_path, matchtitle) File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 197, in unpack_archive if not os.path.isfile(pp_path): # regular files only File "/usr/pbi/lazylibrarian-amd64/lib/python2.7/genericpath.py", line 29, in isfile st = os.stat(path) UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 145: ordinal not in range(128)
2018-06-30 15:56:50 | ERROR | Unhandled exception in processDir: Traceback (most recent call last): File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 455, in processDir res = unpack_archive(os.path.join(pp_path, f), pp_path, matchtitle) File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 197, in unpack_archive if not os.path.isfile(pp_path): # regular files only File "/usr/pbi/lazylibrarian-amd64/lib/python2.7/genericpath.py", line 29, in isfile st = os.stat(path) UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 145: ordinal not in range(128)
2018-06-30 15:46:50 | ERROR | Unhandled exception in processDir: Traceback (most recent call last): File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 455, in processDir res = unpack_archive(os.path.join(pp_path, f), pp_path, matchtitle) File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 197, in unpack_archive if not os.path.isfile(pp_path): # regular files only File "/usr/pbi/lazylibrarian-amd64/lib/python2.7/genericpath.py", line 29, in isfile st = os.stat(path) UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 145: ordinal not in range(128)
2018-06-30 15:36:50 | ERROR | Unhandled exception in processDir: Traceback (most recent call last): File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 455, in processDir res = unpack_archive(os.path.join(pp_path, f), pp_path, matchtitle) File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 197, in unpack_archive if not os.path.isfile(pp_path): # regular files only File "/usr/pbi/lazylibrarian-amd64/lib/python2.7/genericpath.py", line 29, in isfile st = os.stat(path) UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 145: ordinal not in range(128)
2018-06-30 15:26:50 | ERROR | Unhandled exception in processDir: Traceback (most recent call last): File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 455, in processDir res = unpack_archive(os.path.join(pp_path, f), pp_path, matchtitle) File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 197, in unpack_archive if not os.path.isfile(pp_path): # regular files only File "/usr/pbi/lazylibrarian-amd64/lib/python2.7/genericpath.py", line 29, in isfile st = os.stat(path) UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 145: ordinal not in range(128)
2018-06-30 15:16:50 | ERROR | Unhandled exception in processDir: Traceback (most recent call last): File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 455, in processDir res = unpack_archive(os.path.join(pp_path, f), pp_path, matchtitle) File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 197, in unpack_archive if not os.path.isfile(pp_path): # regular files only File "/usr/pbi/lazylibrarian-amd64/lib/python2.7/genericpath.py", line 29, in isfile st = os.stat(path) UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 145: ordinal not in range(128)
2018-06-30 15:06:50 | ERROR | Unhandled exception in processDir: Traceback (most recent call last): File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 455, in processDir res = unpack_archive(os.path.join(pp_path, f), pp_path, matchtitle) File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 197, in unpack_archive if not os.path.isfile(pp_path): # regular files only File "/usr/pbi/lazylibrarian-amd64/lib/python2.7/genericpath.py", line 29, in isfile st = os.stat(path) UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 145: ordinal not in range(128)
2018-06-30 14:56:50 | ERROR | Unhandled exception in processDir: Traceback (most recent call last): File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 455, in processDir res = unpack_archive(os.path.join(pp_path, f), pp_path, matchtitle) File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 197, in unpack_archive if not os.path.isfile(pp_path): # regular files only File "/usr/pbi/lazylibrarian-amd64/lib/python2.7/genericpath.py", line 29, in isfile st = os.stat(path) UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 145: ordinal not in range(128)
2018-06-30 14:46:50 | WARNING | (getLatestVersion_FromGit) Could not get the latest commit from github
2018-06-30 14:46:49 | WARNING | cryptography: module missing
2018-06-30 14:46:49 | WARNING | OpenSSL missing module/attribute: No module named OpenSSL.SSL
2018-06-30 14:46:49 | WARNING | pyOpenSSL: module missing
[/code]

**Comment by philborman** [comment]
Enable debugging, level 2 should be enough, and try the "check version" button on the config page, should show what's going on. Also maybe try with bookstrap interface in case it's related to the legacy one which doesn't get much testing these days. Shouldn't be that, but you never know...

**Comment by famewolf** [comment]
Previous comment updated with correct portion of the log with check update done.  Not familiar with "bookstrap interface" so you'd have to point me in right direction.

**Comment by philborman** [comment]
The problem in the log is SSL error
Will need to look into it and get back to you. What operating system are you running lazylibrarian on?

Bookstrap interface is probably not relevant to this, but it's a much more modern interface and many of the new features in lazylibrarian are only in the new interface. Select it from the dropdown box on the first page of lazylibrarian config.

**Comment by famewolf** [comment]
I am running it on a Freenas server using a precompiled/assembled plugin in a jail.  Freenas is based on freebsd.  The original install was quite some time back and then the package has been self updating itself since.

**Comment by philborman** [comment]
I don't think there are an recent changes to the ssl section in lazylibrarian, but there were some changes 3 months ago, and some more 6 months ago that might be relevant. What version of lazylibrarian are you running (so we know when the update last worked). Would narrow down where to look.

Also now you have the bookstrap interface running can you try the "System Info" button on the config page (bottom of the interface tab). What version of "requests" does it say in the popup, and anything in there about ssl?

**Comment by philborman** [comment]
Sorry, just updating my previous reply as you were sending this, see the new reply :-)

**Comment by famewolf** [comment]
The TLS issue seems to be a vicious circle.  I installed pip into the jail and tried running the commands you indicated:

# pip install requests
Collecting requests
  Could not fetch URL https://pypi.python.org/simple/requests/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) - skipping
  Could not find a version that satisfies the requirement requests (from versions: )
No matching distribution found for requests

**Comment by philborman** [comment]
https://pyfound.blogspot.com/2017/01/time-to-upgrade-your-python-tls-v12.html

Need to figure out how to get around this. Needs some thought...

**Comment by famewolf** [comment]
As a last ditch effort I can look into upgrading the jumpdrive the nas boots off of to the latest version.   I'm currently on 9.10 with the latest being 11.1 however my usual opinion is "if it ain't broke don't fix it."   All other plugins such as sabnzbd, sickrage, couchpotato, nzbhydra etc along with the 20TB of storage continue to work as expected so not in a hurry to possibly screw that up.

I do appreciate all the effort on your part however.

**Comment by philborman** [comment]
I agree, major upgrades are best avoided unless essential, and no guarantee it would fix this particular issue anyway. The problem seems to be the old version of python used in the freenas os. Later versions of python include tls 1.2 by default. Might be possible to upgrade the version of python used in the lazylibrarian jail?

Would be simpler to periodically upgrade lazylibrarian from a zipfile, but you will hit other issues if more sites disable tls 1.0 eg goodreads or some of your torrent providers

Had a quick look at sickrage (sickbeard/couchpotato/headphones/lazylibrarian all started from a common code base years ago) and it uses http to talk to git for updates, not https like we do, but git have talked about forcing https access for a while now.  nzbhydra uses https though, wonder how they get around it, or do updates not work with that either?

**Comment by philborman** [comment]
Another thing you could try, purely as a test, not a proper fix...
Edit lazylibrarian/versioncheck.py  and change all occurrences of https://  to http://
If that lets you past the error the upgrade will still not work (it will complain there are local changes)  but I can set the code to try https first and then http if https fails. Might work?

**Comment by famewolf** [comment]
I changed it to http as requested.....how's this for a path:  /usr/local/share/lazylibrarian/LazyLibrarian/lazylibrarian

Timestamp | Level | Message
-- | -- | --
2018-07-01 12:04:09 | INFO | Debug log OFF, loglevel is 1
2018-07-01 12:03:40 | DEBUG | Update check complete
2018-07-01 12:03:40 | DEBUG | (getCommitDifferenceFromGit) - exiting with commit value of [0]
2018-07-01 12:03:40 | INFO | Unable to get latest version from GitHub
2018-07-01 12:03:40 | DEBUG | git SSLError for http://api.github.com/repos/dobytang/lazylibrarian/commits/master: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:581)
2018-07-01 12:03:40 | WARNING | (getLatestVersion_FromGit) Could not get the latest commit from github
2018-07-01 12:03:39 | DEBUG | (getLatestVersion_FromGit) Checking if modified since Sat, 10 Feb 2018 19:29:11 GMT
2018-07-01 12:03:39 | DEBUG | (getLatestVersion_FromGit) Retrieving latest version information from github command=[http://api.github.com/repos/dobytang/lazylibrarian/commits/master]
2018-07-01 12:03:39 | DEBUG | (getCurrentVersion) - Install type [source] Local Version is unchanged [b53cbb15f05265e21c022a4d9c20310b8a6949b7]
2018-07-01 12:03:39 | DEBUG | (updateVersionFile) Updating [/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/version.txt] with value [b53cbb15f05265e21c022a4d9c20310b8a6949b7]
2018-07-01 12:03:39 | DEBUG | (getInstallType) [source] install detected. Setting Branch to [master]
2018-07-01 12:03:39 | DEBUG | Set Install Type, Current & Latest Version and Commit status
2018-07-01 12:03:28 | INFO | Debug log ON, loglevel is 2

**Comment by philborman** [comment]
I'm guessing git redirects you to https. Oh well, it was worth a try.
One final thing you could try, if you don't mind, in the same versioncheck file near the top is a block 
```
try:
    import requests
except ImportError:
    import lib.requests as requests
```
If you swap those over so the first try is  import lib.requests as requests 
It will use a "local" copy of requests instead of the "jail" copy, does it make any difference?

**Comment by famewolf** [comment]
Did you intend me to switch back to https when the swap was done because I didn't.   Swapped them out and after getting the indentation right so it restarted got the following log:


Timestamp | Level | Thread | File | Method | Line No | Message
-- | -- | -- | -- | -- | -- | --
2018-07-01 20:01:39 | DEBUG | UPDATES | versioncheck.py | logmsg | 45 | Update check complete
2018-07-01 20:01:39 | DEBUG | UPDATES | versioncheck.py | logmsg | 45 | (getCommitDifferenceFromGit) - exiting with commit value of [0]
2018-07-01 20:01:39 | INFO | UPDATES | versioncheck.py | logmsg | 43 | Unable to get latest version from GitHub
2018-07-01 20:01:39 | DEBUG | UPDATES | versioncheck.py | logmsg | 45 | git SSLError for http://api.github.com/repos/dobytang/lazylibrarian/commits/master: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:581)
2018-07-01 20:01:39 | WARNING | UPDATES | versioncheck.py | logmsg | 47 | (getLatestVersion_FromGit) Could not get the latest commit from github
2018-07-01 20:01:39 | DEBUG | UPDATES | versioncheck.py | logmsg | 45 | (getLatestVersion_FromGit) Checking if modified since Sat, 10 Feb 2018 19:29:11 GMT
2018-07-01 20:01:39 | DEBUG | UPDATES | versioncheck.py | logmsg | 45 | (getLatestVersion_FromGit) Retrieving latest version information from github command=[http://api.github.com/repos/dobytang/lazylibrarian/commits/master]
2018-07-01 20:01:39 | DEBUG | UPDATES | versioncheck.py | logmsg | 45 | (getCurrentVersion) - Install type [source] Local Version is unchanged [b53cbb15f05265e21c022a4d9c20310b8a6949b7]
2018-07-01 20:01:39 | DEBUG | UPDATES | versioncheck.py | logmsg | 45 | (updateVersionFile) Updating [/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/version.txt] with value [b53cbb15f05265e21c022a4d9c20310b8a6949b7]
2018-07-01 20:01:39 | DEBUG | UPDATES | versioncheck.py | logmsg | 45 | (getInstallType) [source] install detected. Setting Branch to [master]
2018-07-01 20:01:39 | DEBUG | UPDATES | versioncheck.py | logmsg | 45 | Set Install Type, Current & Latest Version and Commit status
2018-07-01 20:01:32 | INFO | WEBSERVER | webServe.py | toggleLog | 2908 | Debug log ON, loglevel is 2

**Comment by famewolf** [comment]
Oh I noticed nzbhydra was using an http proxy so I tried the same proxy in lazylibrarian using both the original versioncheck.py and the modded one but didn't seem to change anything.  I did NOT check the "enable http proxy" box because for some reason I recall in a previous conversation that didn't work the way I thought it did so this was perhaps a useless test.

**Comment by philborman** [comment]
Ok, thanks for trying. Seems the local requests library still uses the same version of TLS. Switching back to http doesn't matter for the test as git redirects http calls to https.  The "enable http proxy" box depends on what proxy you are using. Needs to be left unchecked for nginx. FWIW the latest lazylibrarian shows the tls version in the system info popup, but I think it will only confirm what we already know.

I think I might need to go through nzbhydra sources to see how they do it

**Comment by philborman** [comment]
https://forums.freenas.org/index.php?threads/help-updating-openssl-in-a-freenas-9-3-jail.63285/
looks like the same problem, seems we are not going to solve this without upgrading freenas

nzbhydra doesn't do anything special, just uses the system version of requests, so presumably it doesn't need tls > 1.0 for the sites it's talking to. I will close this as it's not something lazylibrarian can work around, but let me know if you get it fixed and we can put something in the wiki to help others with the same problem. Thanks.
