### ISSUE TITLE
LazyLibrarian not sending to Sabnzbd Freenas

### ISSUE THREAD

**Issue by naq90** [DobyTang/LazyLibrarian#499]
I am using the LazyLibrarian plug in on Freenas and it is not connecting to sab (also on freenas). These are my sab settings and below are errors i get in the log file.

```
SABnzbd Host: http://192.168.1.5 
SABnzbd Port: 8080
SABnzbd Username: ****
SABnzbd Password:  ***
SABnzbd API: ****
SABnzbd Category:books 
SABnzbd SubDir: 
Retention Max Age:
```

Logs:   

```
2016-10-13 20:39:34 DEBUG   Sending Nzbfile to SAB URL
2016-10-13 20:39:24 DEBUG   Sending Nzbfile to SAB URL
2016-10-13 20:39:16 DEBUG   Sending Nzbfile to SAB URL
2016-10-13 20:38:22 DEBUG   Sending Nzbfile to SAB URL
```

and later in the log file i get:

```
2016-10-13 20:38:15 DEBUG   Request url for SABnzbd
2016-10-13 20:38:14 DEBUG   Request url for SABnzbd
2016-10-13 20:38:14 DEBUG   Request url for SABnzbd
2016-10-13 20:38:14 DEBUG   Request url for SABnzbd
```

The problem is not with finding NZBs however as the logs show that there are ones available:

```
2016-10-13 20:38:47 DEBUG   Found 7 nzb at https://pfmonkey.com for: Joseph Heller Catch-22
2016-10-13 20:37:44 DEBUG   Found 7 nzb at https://pfmonkey.com for: Joseph Heller Catch-22
2016-10-13 20:38:53 DEBUG   Found 9 nzb at https://api.oznzb.com for: Joseph Heller Catch-22
2016-10-13 20:38:50 DEBUG   Found 9 nzb at https://api.oznzb.com for: Joseph Heller Catch-22
```

The problem is none of these are being sent to sab. Any idea on how to remedy this?

**Comment by philborman** [comment]
Wow, I really screwed that up - it's been broken for a couple of weeks now. 
I've just rewritten the code that communicates with sab, a bit more testing and I will push an update later today.

**Comment by philborman** [comment]
ok, should be fixed now.

**Comment by naq90** [comment]
wow that was quick! Will try it later today. Thanks man

**Comment by philborman** [comment]
There are a few other updates included in this release, in particular a
database update which takes a while.

Once that's completed, try the "test sabnzbd" button on the config page. If
it says it connected ok  you should be good to go.

If all is ok (should be!), please close the issue on the github page.
Thanks.

**Comment by naq90** [comment]
So the test sabnzbd connection worked successfully. However, after finding a nzb file it still does not send to sab.

**Comment by philborman** [comment]
anything in the debug log that might help? Seems to be working here ok

**Comment by naq90** [comment]
This is what's in the log. I don't know if there's anything of use though. 

```
2016-10-14 15:54:25	DEBUG	Requesting capabilities for https://nzb.su//api?t=caps&apikey=6c61438072d2846ebf262c7166b1608a
2016-10-14 15:54:25	DEBUG	Found 3 nzb at https://api.oznzb.com for: Daniel Keyes Flowers for Algernon
2016-10-14 15:54:25	DEBUG	[NewzNabPlus] - result fields from NZB are {'bookid': u'18373', 'nzbmode': 'nzb', 'nzbdate': 'Mon, 18 Feb 2013 07:58:10 +1000', 'nzbtitle': 'Daniel Keyes - Flowers for Algernon (epub)', 'nzbsize': '267064', 'nzburl': 'https://api.oznzb.com/getnzb/0737a46da69befc54c3c11c0d27d0849.nzb&i=223202&r=a44d4e43d09268b4f9f67b01b44e681b', 'nzbprov': u'https://api.oznzb.com'}
2016-10-14 15:54:25	DEBUG	[NewzNabPlus] - result fields from NZB are {'bookid': u'18373', 'nzbmode': 'nzb', 'nzbdate': 'Mon, 18 Feb 2013 07:20:34 +1000', 'nzbtitle': 'Daniel Keyes - Flowers for Algernon (mobi)', 'nzbsize': '342183', 'nzburl': 'https://api.oznzb.com/getnzb/07731dc0db7202dfbaf932243fe1dd48.nzb&i=223202&r=a44d4e43d09268b4f9f67b01b44e681b', 'nzbprov': u'https://api.oznzb.com'}
2016-10-14 15:54:25	DEBUG	[NewzNabPlus] - result fields from NZB are {'bookid': u'18373', 'nzbmode': 'nzb', 'nzbdate': 'Mon, 18 Feb 2013 07:58:10 +1000', 'nzbtitle': 'Daniel Keyes - Flowers for Algernon (v5.0) (epub)', 'nzbsize': '223497', 'nzburl': 'https://api.oznzb.com/getnzb/420fb6323e3bf40846085900b9375a5e.nzb&i=223202&r=a44d4e43d09268b4f9f67b01b44e681b', 'nzbprov': u'https://api.oznzb.com'}
2016-10-14 15:54:25	DEBUG	Parsing results from https://api.oznzb.com
2016-10-14 15:54:23	DEBUG	[NewzNabPlus] - nzb Search parameters set to {'author': u'Daniel Keyes', 'apikey': u'a44d4e43d09268b4f9f67b01b44e681b', 't': u'book', 'cat': u'7000,7020', 'title': u'Flowers for Algernon'}
2016-10-14 15:54:23	DEBUG	[NewzNabPlus] searchType [book] with Host [https://api.oznzb.com] mode [nzb] using api [a44d4e43d09268b4f9f67b01b44e681b] for item [{'bookSub': u'', 'searchterm': u'Daniel Keyes Flowers for Algernon', 'bookName': u'Flowers for Algernon', 'authorName': u'Daniel Keyes', 'bookid': u'18373'}]
```

**Comment by philborman** [comment]
Well, you are right, there isn't anything of use there.
That's the section that locates the file to grab. Later on there should be at least 3 lines like this showing communication with SAB. If you don't see all three it would be useful to know which one it stops at, as the problem must be after that point...

15-Oct-2016 14:38:01 - DEBUG   :: SEARCHNZB : Request url for <a href="http://192.168.2.2:8080/api?nzbname=Henri+Charriere+-+Papillon+LL.%286882%29&ma_password=xxxxx&apikey=xxxxxxxxxxxxxxx&name=http%3A%2F%2F192.168.2.2%3A8086%2Fnzbhydra%2Fgetnzb%3Fapikey%3Dxxxxxxxxxxxxxxxxxxxxxxxxxxxx%26searchresultid%3D66141&cat=books&mode=addurl&output=json&ma_username=phil">SABnzbd</a>
15-Oct-2016 14:38:01 - DEBUG   :: SEARCHNZB : Sending Nzbfile to SAB <a href="http://192.168.2.2:8080/api?nzbname=Henri+Charriere+-+Papillon+LL.%286882%29&ma_password=xxxxxxxx&apikey=xxxxxxxxxxxxxxxxxxxxxxxxxxxx&name=http%3A%2F%2F192.168.2.2%3A8086%2Fnzbhydra%2Fgetnzb%3Fapikey%3Dxxxxxxxxxxxxxxxxxxxxxxxxxxxxx%26searchresultid%3D66141&cat=books&mode=addurl&output=json&ma_username=phil">URL</a>
15-Oct-2016 14:38:01 - DEBUG   :: SEARCHNZB : Result text from SAB: {u'status': True, u'nzo_ids': [u'SABnzbd_nzo_5_hfyr']}

**Comment by naq90** [comment]
Should those three lines show up after testing the Sab connection in settings? Or when there is an nzb file that has been grabbed and needs to be sent?

**Comment by philborman** [comment]
Should be when you send a file to sab to download.

**Comment by philborman** [comment]
ok, may have found this problem. Seems not all versions of sab return the nzo_ids, which will cause the download task to crash. Any idea what version of sabnzbd you are running? Current is 1.1.0
I have has a report that shows sab returning  
Result text from SAB: {u'status': True}
when we are expecting something like
Result text from SAB: {u'status': True, u'nzo_ids': [u'SABnzbd_nzo_5_hfyr']}

**Comment by philborman** [comment]
Should be fixed in latest release. The "delete files" function needs sabnzbd >= 0.8.0
Earlier versions of sabnzbd will work as downloaders, but we won't try to delete anything on them
