### ISSUE TITLE
Database error: table seriesauthors already exists

### ISSUE THREAD

**Issue by exodius99** [DobyTang/LazyLibrarian#756]
VERSION: 14a234e22fd1bd2503d035aa62a9aa7339347c4d
OS: Windows
API: Goodreads

I had I believe 9 commits available so I clicked update and after the update had completed my authors now do not show any books and will not update. I checked the logs and found the errors during the database. Not sure why my database would have been so many upgrades behind since I keep it updated pretty well.

[log.txt](https://github.com/DobyTang/LazyLibrarian/files/962505/temp.txt)

**Comment by philborman** [comment]
Your log says upgrading database v13 to v19. There was a problem somewhere in v17 upgrade which I think might have been fixed a few days ago, but that may not be working as I don't have an old database to test. Can you check your log directory and see if you have a dbupgrade.log  if so that might help.

**Comment by exodius99** [comment]
Here it is: [dbupgrade.txt](https://github.com/DobyTang/LazyLibrarian/files/962995/dbupgrade.txt)

**Comment by philborman** [comment]
Ok thanks, that found it, will push a fix tomorrow. You should be able to
upgrade lazylibrarian and the database will correct itself.

**Comment by philborman** [comment]
Just pushed a new version that hopefully fixes it. Can you let me know if it works as expected. Thanks

**Comment by exodius99** [comment]
Still failing during the v17 upgrade.

[dbupgrade.txt](https://github.com/DobyTang/LazyLibrarian/files/964847/dbupgrade.txt)
[log.txt](https://github.com/DobyTang/LazyLibrarian/files/964850/log.txt)

**Comment by philborman** [comment]
Slightly different problem. Seems your "series" table has an entry where the author is None (shouldn't happen). I guess this is the result of the previously failed upgrades. I will add some code to filter out the bad data, shouldn't take long.

**Comment by exodius99** [comment]
Could have possible been when the database wasn't updating correctly and I tried adding a new author before I realized that?

Whatever the case everything seems to be running fine after the update last night. Thank you very much for your help.

**Comment by philborman** [comment]
Thanks for your help and all the testing.
